# Generated by Django 5.0.14 on 2026-10-02 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_intervals', models.JSONField(blank=True, default=list, help_text='List of days before/after due date, e.g. [-3,0,3,7]')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('max_contacts_per_day', models.IntegerField(default=2)),
                ('max_contacts_per_week', models.IntegerField(default=5)),
                ('escalate_after_attempts', models.IntegerField(default=3)),
                ('auto_pause_on_payment', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_policy', to='tenancy.organization')),
            ],
            options={
                'db_table': 'collection_policies',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='collection_campaigns', to='tenancy.organization')),
            ],
            options={
                'db_table': 'collection_campaigns',
                'indexes': [models.Index(fields=['org', 'status'], name='collection__org_id_615c6b_idx')],
            },
        ),
    ]
