# Generated by Django 5.0.14 on 2026-10-02 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overdue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prefs', models.JSONField(blank=True, default=dict)),
                ('communication_preference', models.JSONField(blank=True, default=dict)),
                ('opt_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('language_detection_enabled', models.BooleanField(default=True)),
                ('language_updated_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
