# Generated by Django 5.0.14 on 2026-10-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_language',
            field=models.ForeignKey(blank=True, db_column='preferred_language', default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='customers_preferred', to='languages.language'),
        ),
        migrations.AddField(
            model_name='customer',
            name='voice_language',
            field=models.ForeignKey(blank=True, db_column='voice_language', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='customers_voice', to='languages.language'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['org', 'customer_code'], name='customers_org_id_2d0176_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['org', 'name'], name='customers_org_id_f32411_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['org', 'preferred_language'], name='customers_org_id_17a619_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['preferred_language'], name='customers_preferr_f47187_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('org', 'customer_code'), name='uniq_customer_code_per_org'),
        ),
    ]
