# Generated by Django 5.0.14 on 2026-09-27 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('languages', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('provider_call_id', models.CharField(blank=True, default='', max_length=128)),
                ('from_number', models.CharField(blank=True, default='', max_length=32)),
                ('to_number', models.CharField(blank=True, default='', max_length=32)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, default='')),
                ('cost_minor', models.IntegerField(blank=True, null=True)),
                ('language_source', models.CharField(blank=True, default='', help_text='customer_voice_pref | customer_pref | conversation | org_default | fallback', max_length=24)),
                ('voice_id', models.CharField(blank=True, default='', help_text='TTS voice actually used', max_length=64)),
                ('voice_provider', models.CharField(blank=True, default='', max_length=32)),
                ('voice_usable', models.BooleanField(default=True, help_text='False when no native voice existed and we should not have called (§22)')),
                ('detected_language', models.CharField(blank=True, default='', help_text="Language detected from the customer's speech (§10)", max_length=10)),
                ('stt_confidence', models.DecimalField(blank=True, decimal_places=3, help_text='Speech-to-text confidence for the last turn (§10)', max_digits=4, null=True)),
                ('language_switch_count', models.PositiveIntegerField(default=0, help_text='Spoken language switches (§9 step 6)')),
                ('escalated', models.BooleanField(default=False, help_text='Agent handed off to a human (§23)')),
                ('escalation_reason', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='invoices.invoice')),
                ('language', models.ForeignKey(blank=True, help_text='Language the agent spoke on this call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='languages.language')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'db_table': 'voice_calls',
            },
        ),
        migrations.CreateModel(
            name='CallAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('stt_text', models.TextField(blank=True, default='')),
                ('stt_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('detected_language', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='call_attempts', to='tenancy.organization')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='voice.voicecall')),
            ],
            options={
                'db_table': 'call_attempts',
                'ordering': ['attempt_number'],
            },
        ),
        migrations.AddIndex(
            model_name='voicecall',
            index=models.Index(fields=['org', 'status'], name='voice_calls_org_id_a18374_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecall',
            index=models.Index(fields=['org', 'language'], name='voice_calls_org_id_e4380f_idx'),
        ),
    ]
