# Generated by Django 5.0.14 on 2026-10-02 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('voice', 'Voice')], max_length=16)),
                ('template_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('provider_msg_id', models.CharField(blank=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('cost_minor', models.IntegerField(blank=True, help_text='Cost in kobo', null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('language', models.CharField(blank=True, default='', help_text='Language the message was rendered in (empty = resolved at send time)', max_length=10)),
                ('language_source', models.CharField(blank=True, default='', help_text='event_override | customer_preferred | org_default | fallback', max_length=24)),
                ('body_snapshot', models.TextField(blank=True, default='', help_text='Exact text sent - preserved so a dispute can be reconstructed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communication_events',
            },
        ),
        migrations.CreateModel(
            name='CommunicationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('voice', 'Voice')], max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communication_preferences',
            },
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Reminder rule', max_length=128)),
                ('trigger', models.CharField(choices=[('before_due', 'Before due'), ('on_due', 'On due date'), ('after_due', 'After due')], default='on_due', max_length=16)),
                ('offset_days', models.IntegerField(default=0, help_text='Days before (negative) or after due date. 0=on due')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('voice', 'Voice')], default='whatsapp', max_length=16)),
                ('template', models.TextField(default='Hello {{customer_name}}, invoice {{invoice_number}} for {{amount_due}} is due on {{due_date}}. Pay: {{payment_link}}')),
                ('language', models.CharField(default='auto', help_text='auto=customer preferred, or en/ha/yo/ig', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reminder_rules',
            },
        ),
    ]
