# Generated by Django 5.0.14 on 2026-10-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comms', '0001_initial'),
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationevent',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm_events', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='communicationevent',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm_events', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='communicationevent',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='communicationpreference',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_preferences', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='communicationpreference',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_preferences', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='reminderrule',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='tenancy.organization'),
        ),
        migrations.AddIndex(
            model_name='communicationevent',
            index=models.Index(fields=['org', 'channel'], name='communicati_org_id_a36464_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationevent',
            index=models.Index(fields=['org', 'status'], name='communicati_org_id_6535d5_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationevent',
            index=models.Index(fields=['org', 'language'], name='communicati_org_id_578232_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communicationpreference',
            unique_together={('org', 'customer', 'channel')},
        ),
        migrations.AddIndex(
            model_name='reminderrule',
            index=models.Index(fields=['org', 'enabled'], name='reminder_ru_org_id_77d685_idx'),
        ),
    ]
