# Generated by Django 5.0.14 on 2026-10-02 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual')], max_length=32)),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature', models.CharField(blank=True, default='', max_length=512)),
                ('processed', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'processed'], name='webhook_eve_provide_fed522_idx')],
            },
        ),
    ]
