# Generated by Django 5.0.14 on 2026-10-02 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgentAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool', models.CharField(help_text='Tool/function name', max_length=128)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('tokens', models.IntegerField(blank=True, null=True)),
                ('cost_minor', models.IntegerField(blank=True, null=True)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_agent_actions',
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('INVOICE_CREATED', 'Invoice Created'), ('REMINDER_SENT', 'Reminder Sent'), ('CUSTOMER_REPLIED', 'Customer Replied'), ('NEGOTIATING', 'Negotiating'), ('PROMISE_MADE', 'Promise Made'), ('PROMISE_DUE', 'Promise Due'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('ESCALATED', 'Escalated'), ('HUMAN_HANDOFF', 'Human Handoff'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled'), ('FOLLOW_UP', 'Follow Up'), ('OVERDUE_NOTICE', 'Overdue Notice'), ('COLLECTION_CLOSED', 'Collection Closed')], default='INVOICE_CREATED', max_length=32)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('voice', 'Voice')], default='whatsapp', max_length=16)),
                ('language_source', models.CharField(blank=True, choices=[('customer_preferred', 'Customer Preferred'), ('detected', 'Detected'), ('conversation_memory', 'Conversation Memory'), ('business_fallback', 'Business Fallback'), ('system_fallback', 'System Fallback')], default='', help_text='How conversation_language was chosen (audit + §20 continuity)', max_length=24)),
                ('language_switch_count', models.PositiveIntegerField(default=0, help_text='Number of detected language switches in this conversation (§8)')),
                ('code_switch_count', models.PositiveIntegerField(default=0, help_text='Number of mixed-language messages seen (§27)')),
                ('language_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_conversations',
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], default='user', max_length=16)),
                ('content', models.TextField()),
                ('tokens', models.IntegerField(blank=True, null=True)),
                ('language_confidence', models.DecimalField(blank=True, decimal_places=3, help_text='Detection confidence 0-1 (§7)', max_digits=4, null=True)),
                ('is_code_switched', models.BooleanField(default=False, help_text='Message mixed two languages (§27)')),
                ('was_language_switch', models.BooleanField(default=False, help_text="Language differed from the conversation's established language (§8)")),
                ('staff_translation', models.TextField(blank=True, default='', help_text="AI translation of `content` into the business owner's language (§33)")),
                ('staff_translation_language', models.CharField(blank=True, default='', help_text='Language of staff_translation', max_length=10)),
                ('staff_translation_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('escalated', models.BooleanField(default=False, help_text='Low-confidence language handling triggered (§23)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromiseToPay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promise_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('kept', 'Kept'), ('broken', 'Broken'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'promise_to_pay',
            },
        ),
    ]
