# Generated by Django 5.0.14 on 2026-09-27 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('languages', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='conversation_language',
            field=models.ForeignKey(blank=True, help_text='Language currently being used in this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversation_current', to='languages.language'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='preferred_language',
            field=models.ForeignKey(blank=True, help_text='Snapshot of customer preferred_language at conversation start', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversation_preferred', to='languages.language'),
        ),
        migrations.AddField(
            model_name='aiagentaction',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ai.aiconversation'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='detected_language',
            field=models.ForeignKey(blank=True, help_text='Language detected from the inbound text (§6)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_messages_detected', to='languages.language'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Language this message was written in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_messages', to='languages.language'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='secondary_language',
            field=models.ForeignKey(blank=True, help_text='Second language present in a mixed-language message (§27)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_messages_secondary', to='languages.language'),
        ),
        migrations.AddField(
            model_name='promisetopay',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='ai.aiconversation'),
        ),
        migrations.AddField(
            model_name='promisetopay',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='promisetopay',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='promisetopay',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='promises', to='tenancy.organization'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['org', 'state'], name='ai_conversa_org_id_94c024_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['org', 'conversation_language'], name='ai_conversa_org_id_cf3d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_messages_convers_15163f_idx'),
        ),
    ]
