# Generated by Django 5.0.14 on 2026-10-02 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICommunicationAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_selected', models.CharField(blank=True, default='', help_text='Language used for the reply', max_length=10)),
                ('language_detected', models.CharField(blank=True, default='', help_text='Language detected from customer input', max_length=10)),
                ('secondary_language', models.CharField(blank=True, default='', help_text='Second language present (code-switch, S27)', max_length=10)),
                ('detection_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('language_source', models.CharField(blank=True, default='', help_text='How the language was chosen (S5)', max_length=24)),
                ('channel', models.CharField(blank=True, default='', max_length=16)),
                ('ai_model', models.CharField(blank=True, default='', help_text='e.g. gpt-4o-mini', max_length=64)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=64)),
                ('template_id', models.CharField(blank=True, default='', max_length=64)),
                ('request_summary', models.TextField(blank=True, default='', help_text='Redacted/truncated input')),
                ('response_text', models.TextField(blank=True, default='', help_text='What the AI actually sent')),
                ('translation_status', models.CharField(blank=True, default='', help_text='none | generated | staff_viewed', max_length=24)),
                ('staff_translation', models.TextField(blank=True, default='', help_text='Staff-facing rendering (S33)')),
                ('voice_provider', models.CharField(blank=True, default='', max_length=32)),
                ('voice_id', models.CharField(blank=True, default='', max_length=64)),
                ('stt_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('call_status', models.CharField(blank=True, default='', max_length=16)),
                ('recording_url', models.CharField(blank=True, default='', help_text='Expires per retention policy', max_length=256)),
                ('outcome', models.CharField(blank=True, choices=[('sent', 'Sent'), ('received', 'Received'), ('escalated', 'Escalated'), ('human_handoff', 'Handled By Human'), ('failed', 'Failed')], default='', max_length=24)),
                ('escalated', models.BooleanField(default=False)),
                ('escalation_reason', models.CharField(blank=True, choices=[('low_confidence', 'Low Confidence'), ('no_native_voice', 'No Native Voice'), ('customer_request', 'Customer Request'), ('dispute', 'Dispute'), ('stt_unreliable', 'Speech Recognition Unreliable')], default='', max_length=24)),
                ('corrected', models.BooleanField(default=False, help_text='A human edited the AI output before sending')),
                ('tokens', models.IntegerField(blank=True, null=True)),
                ('cost_minor', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_communication_audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='e.g. customer.create, invoice.update', max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=128)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
