# Generated by Django 5.0.14 on 2026-10-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('audit', '0001_initial'),
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicommunicationaudit',
            name='comm_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_comm_audits', to='comms.communicationevent'),
        ),
        migrations.AddField(
            model_name='aicommunicationaudit',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_comm_audits', to='ai.aiconversation'),
        ),
    ]
