# Generated by Django 5.0.14 on 2026-09-27 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0002_initial'),
        ('customers', '0001_initial'),
        ('tenancy', '0001_initial'),
        ('voice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aicommunicationaudit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_comm_audits', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='aicommunicationaudit',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_comm_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aicommunicationaudit',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_comm_audits', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='aicommunicationaudit',
            name='voice_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_comm_audits', to='voice.voicecall'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aicommunicationaudit',
            index=models.Index(fields=['org', 'created_at'], name='ai_communic_org_id_bf6cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='aicommunicationaudit',
            index=models.Index(fields=['org', 'language_selected'], name='ai_communic_org_id_f604b4_idx'),
        ),
        migrations.AddIndex(
            model_name='aicommunicationaudit',
            index=models.Index(fields=['customer', 'created_at'], name='ai_communic_custome_3c8e67_idx'),
        ),
        migrations.AddIndex(
            model_name='aicommunicationaudit',
            index=models.Index(fields=['org', 'escalated'], name='ai_communic_org_id_f58832_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='audit_logs_target__9fc8de_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor'], name='audit_logs_actor_i_0badd2_idx'),
        ),
    ]
